### ISSUE TITLE
still working

### ISSUE THREAD

**Issue by darkzbaron** [austin1237/tinder-v1-auth-service#5]
Hi there, desperatly trying to get the token with no success.

**Comment by austin1237** [comment]
I haven't touched this in a couple of months. I can check it out after I get off of work today. There's definitely  lack on documentation for this repo. To help with debugging do you mind telling me what os your running, version of node, version of phantom, version of casper, how your initing the script and what your sending in your request (without giving out your actual fb details).

**Comment by darkzbaron** [comment]
hi , sorry i havent seen your answer until now. Im on Win 10. I tried to run the software by going into command line and run "node tinder-auth-api --port="port number" 3000". All dependencies are installed otherwise. Thanks very much in advance
